// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    ErrorContainer: typeof import('./src/components/ErrorContainer.vue')['default']
    EssentialLink: typeof import('./src/components/EssentialLink.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    QBtn: typeof import('quasar/src/components/btn/QBtn.js')['default']
    QDrawer: typeof import('quasar/src/components/drawer/QDrawer.js')['default']
    QHeader: typeof import('quasar/src/components/header/QHeader.js')['default']
    QIcon: typeof import('quasar/src/components/icon/QIcon.js')['default']
    QInnerLoading: typeof import('quasar/src/components/inner-loading/QInnerLoading.js')['default']
    QItem: typeof import('quasar/src/components/item/QItem.js')['default']
    QItemLabel: typeof import('quasar/src/components/item/QItemLabel.js')['default']
    QItemSection: typeof import('quasar/src/components/item/QItemSection.js')['default']
    QLayout: typeof import('quasar/src/components/layout/QLayout.js')['default']
    QList: typeof import('quasar/src/components/item/QList.js')['default']
    QMenu: typeof import('quasar/src/components/menu/QMenu.js')['default']
    QPage: typeof import('quasar/src/components/page/QPage.js')['default']
    QPageContainer: typeof import('quasar/src/components/page/QPageContainer.js')['default']
    QSeparator: typeof import('quasar/src/components/separator/QSeparator.js')['default']
    QSpinnerPuff: typeof import('quasar/src/components/spinner/QSpinnerPuff.js')['default']
    QToolbar: typeof import('quasar/src/components/toolbar/QToolbar.js')['default']
    QToolbarTitle: typeof import('quasar/src/components/toolbar/QToolbarTitle.js')['default']
  }
}

export { }
